name: test_apps
description: Use delivery app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  freezed: 1.1.0
  intl: 0.17.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-Regular.ttf
    - family: PoppinsBold
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
    - family: SemiBold
      fonts:
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600

